#数据库访问
spring:
  datasource:
    username: root
    password: chenyy
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8


