#数据库访问
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: chenyy
    driver-class-name: com.mysql.jdbc.Driver
  mybatis:
    type-aliases-package: com.myoffer.university.model